server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}
    # openfeign 配置,默认 Read timed out 时间为 60s
    openfeign:
      client:
        config:
          default:
            #连接超时时间 ms
            connectTimeout: 3000
            #读取超时时间 ms,控制 Read timed out  超时
            readTimeout: 3000
          payment-service-5s:
            #连接超时时间 ms
            connectTimeout: 5000
            #读取超时时间 ms,控制 Read timed out  超时
            readTimeout: 5000
          payment-service-10s:
            #连接超时时间 ms
            connectTimeout: 10000
            #读取超时时间 ms,控制 Read timed out  超时
            readTimeout: 10000
#      替换httpclient 如果不做特殊配置，OpenFeign默认使用JDK自带的HttpURLConnection发送HTTP请求，由于默认HttpURLConnection没有连接池、性能和效率比较低
      httpclient:
        hc5:
          enabled: true
